IMAGE_NAME = "hashicorp/bionic64"
N = 2

Vagrant.configure("2") do |config|

    (1..N).each do |machine_id|
        config.vm.define "lamp#{machine_id}" do |machine|
            machine.vm.box = IMAGE_NAME
            machine.vm.hostname = "lamp#{machine_id}"
            machine.vm.network "private_network", ip: "192.168.77.#{20+machine_id}"

            # Only execute once the Ansible provisioner,
            # when all the machines are up and ready.
            if machine_id == N
                machine.vm.provision :ansible do |ansible|
                    # Disable default limit to connect to all the machines
                    ansible.limit = "all"
                    ansible.playbook = "lamp_ubuntu1804/playbook.yml"
                end
            end
        end
    end
end